### ISSUE TITLE
E: Unable to locate package v8dmoj

### ISSUE THREAD

**Issue by int-y1** [DMOJ/runtimes-docker#73]
"Build tier 2 Docker image" is failing because of the error `E: Unable to locate package v8dmoj`. Here's an [example](https://github.com/DMOJ/runtimes-docker/actions/runs/7326534791/job/19952334075#step:5:1600).

It looks like `apt-get update` tried to query https://apt.dmoj.ca but got error 500. I think this caused the v8dmoj error. Here are the logs:

```
#5 497.4 Ign:7 https://apt.dmoj.ca bullseye InRelease
#5 498.8 Ign:7 https://apt.dmoj.ca bullseye InRelease
#5 501.1 Ign:7 https://apt.dmoj.ca bullseye InRelease
#5 505.4 Err:7 https://apt.dmoj.ca bullseye InRelease
#5 505.4   500  Internal Server Error [IP: 172.67.219.125 443]
```

**Comment by quantum5** [comment]
Should be fixed... until the next time it decides to die.
